name:                culinary-quest
version:             0.1.0.0

extra-source-files:
- README.md

description:         culinary-quest

ghc-options:
- -Werror
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns

language: GHC2021

dependencies:
- base >= 4.7 && < 5
- containers
- random
- parsec
- mtl

library:
  source-dirs: src

executables:
  culinary-quest-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - culinary-quest
    when:
    - condition: false
      other-modules: Paths_culinary_quest

tests:
  culinary-quest-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - culinary-quest
    - hspec
    - hspec-discover
    - QuickCheck
